### ISSUE TITLE
TODO for NOAA materializer

### ISSUE THREAD

**Issue by RqS** [usc-isi-i2/datamart#3]
1. `locationid`, `datatypeid` are hard coded if `data_range` is not provided.
https://github.com/usc-isi-i2/datamart/blob/442c8c512a95ba54c2ef45e02f55cf15e1d030a0/datamart/materializers/nooa_materializer.py#L47
Right now, if `data_range` is none, it will always return the same dataset.

2. change `data_range` to `date_range` or `time_range`, the name of `data_range` is misleading

3. Maybe `location` should be a list of locations. By default, it is 'los angeles'
https://github.com/usc-isi-i2/datamart/blob/442c8c512a95ba54c2ef45e02f55cf15e1d030a0/datamart/materializers/nooa_materializer.py#L29
So that, one can query multiple locations later on.

There are changes, please do pull the latest to your fork then do implementation.

**Comment by Zhihaosh** [comment]
Thank you for your suggestions.

**Comment by RqS** [comment]
This is being fixed
