### ISSUE TITLE
Breakdown WorldBank data into chunks for materialization

### ISSUE THREAD

**Issue by RqS** [usc-isi-i2/datamart#50]
Materialize worldbank data for all time across all countries takes too long to finish. Not able to materialize it within acceptable time.
1. Consider break it down for every country. This means we will have a dataset for all time range for a single country, each associates with one metadata. There is already around 16000 datasets. Doing this will make the number of datasets (metadata) become 16000* (#countries). And we need to en`
2. Otherwise, since the dataset is too big for materializing and profiling, we can put a fixed set of countries in the country column as named_entity. But for materialization, need to query with list of named_entities (countries).

We can discuss here for the correct way of dealing with worldbank.

**Comment by szeke** [comment]
Let's do it by country. It is OK if the total number is 16000*200 (countries). My guess is that not all indicators are available for every country. @BhavyaGulati please make the changes.

**Comment by RqS** [comment]
@BhavyaGulati Please confirm you will work on this. If you have any problem or concern, you can post it here or slack me, thanks.

**Comment by RqS** [comment]
See #64
