### ISSUE TITLE
RLTK joiner

### ISSUE THREAD

**Issue by RqS** [usc-isi-i2/datamart#52]
Subclass https://github.com/usc-isi-i2/datamart/blob/35341f8fdb6c6b8232a1a84fa19ba1c765926ead/datamart/joiners/joiner_base.py#L7

Basically it gets 2 dataframes and return a joined one. Detailed inputs need to be confirmed with front end. Will update here. Hold on for a while to start.

**Comment by RqS** [comment]
@Lituta Interface: https://github.com/usc-isi-i2/datamart/blob/development/datamart/joiners/rltk_joiner.py

**Comment by Lituta** [comment]
- For now rltk joiner runs a strict left-join. The output table will have the same number of rows as the left table. 
- For each left row, it will be augmented by the row in the right table with highest average similarity among joining features, if the average similarity is over a threshold. So, if there are many "best" matches, a random one will be picked; if there is no over-threshold similarity match, it will be filled with None.
