### ISSUE TITLE
Noaa is not able to return data more than one year with single query

### ISSUE THREAD

**Issue by RqS** [usc-isi-i2/datamart#54]
Noaa is not able to return data more than one year with single query, using multiple queries to return dataset for all years by default is not possible either (too big).

In this case, if users want to join their datasets with NOAA. We need a time range for querying data.

We need to form queries by each year if the input time range is more than a year in `noaa_materializer`. And by defaut, it returns the last year maybe.

But still, how we gonna get the time range? Another user input from UI? 

Or break down NOAA data by year. Then with current system, we may not able to find dataset for join, we need to getting the cluster metadata working for multiple years data

**Comment by szeke** [comment]
@RqS We need to figure out a solution for datasets that are partitioned by period, country or some other attribute. My proposal is to have @Zhihaosh index each year as a separate dataset and for us on the indexing side to figure out a solution. I'll think about it this evening.

**Comment by RqS** [comment]
Maybe the cluster metadata is still the solution. 
1. We need to profile the provided dataset with its temporal and named_entity coverage.
2. Construct our query to hit the cluster metadata
3. Then we form multiple materializer.get and stack datasets if necessary.
4. Join

**Comment by RqS** [comment]
See #64
