### ISSUE TITLE
Conda environment checksums

### ISSUE THREAD

**Issue by juancroldan** [usc-isi-i2/datamart#55]
The `enviroment.yml` includes checksums for specific versions of the packages which are probably the OSX versions. Removing the checksums solves this problem for Ubuntu 16.04 and Windows 7.
For instance, changing `libffi=3.2.1=h475c297_4` to `libffi=3.2.1` allows me to install it.

**Comment by RqS** [comment]
Thanks for pointing out!
I will remove suffix and tested on OSX system and change it.

**Comment by RqS** [comment]
removed checksums

**Comment by juancroldan** [comment]
For those OSX-specific lines, you can use [Conda preprocessing selectors](https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#preprocessing-selectors).

If you add `# [osx]` at the end of those lines, they will only be interpreted when the platform is macOS.
