### ISSUE TITLE
Wikidata

### ISSUE THREAD

**Issue by RqS** [usc-isi-i2/datamart#71]
@linqyd Please update the Wikidata progress and todos here, and communicate with @Lituta about this.

**Comment by linqyd** [comment]
Done:
1. script to generate wikidata dataset schema with all ids.
2. script to generate wikidata dataset scheme with only spo.
(Both will record timeout property to error log.)
3. materializer for wikidata dataset with all ids. (doesn't use 'LIMIT' to get partial dataset)
4. materializer for wikidate dataset with only spo. (use 'LIMIT', can get partial dataset)

TODO:
run schema_generator.py to create all dataset schema

**Comment by Lituta** [comment]
the spo schema generator works well, will start to index when all the schemas are generated.
